services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/invoice:cached
    depends_on:
      - db
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: codespace
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: